version: '3.8'

services:
  # Backend FastAPI - Se conecta a PostgreSQL del host
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sunat_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: host.docker.internal
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
